//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrmerWatchGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class RecipientSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RecipientSettings defaultInstance = ((RecipientSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RecipientSettings())));
        
        public static RecipientSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ross.higgins@nhs.net")]
        public string Recipient1 {
            get {
                return ((string)(this["Recipient1"]));
            }
            set {
                this["Recipient1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("someperson@nhs.net")]
        public string Recipient2 {
            get {
                return ((string)(this["Recipient2"]));
            }
            set {
                this["Recipient2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("anotherperson@nhs.net")]
        public string Recipient3 {
            get {
                return ((string)(this["Recipient3"]));
            }
            set {
                this["Recipient3"] = value;
            }
        }
    }
}
